### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by bmviniciuss** [bmviniciuss/reebit-api#1]
# TODO
- [X] LoadUserByEmailRepository
- [X] RegisterUserRepository
- [x] Separate factories on it's own files
- [x] Plan new strategy to controller factories and graphqlAdapter
- [x] Remove HttpRequest from Controller and receive the input data as parameter on `handle` method
