### ISSUE TITLE
User Confirmation

### ISSUE THREAD

**Issue by bmviniciuss** [bmviniciuss/reebit-api#3]
User should make the mutation to confirm their registration with the code sent by email.

## Tasks
- [x] Add mutation schema
- [x] Add user confirmation controller
- [x] Add user confirmation use-case
- [x] Create redis `get` repository method
- [x] Create verify user repository
- [x] Add tests
- [x] Revoke registry from redis
