### ISSUE TITLE
Remove Redis

### ISSUE THREAD

**Issue by bmviniciuss** [bmviniciuss/reebit-api#6]
## Task
- Remove `Redis` from codebase.

### Details
- Use `MongoDB` to save the user confirmation code.
- Generate a JWT token with expiration date to use as a magic-link.
```
# users_confirmation collection
_id -> ObjectId
userId -> ObjectId
hash -> String (JWT token with 15min expiration time)
confirmationCode -> String (6 characters random)
createdAt -> Date
updatedAt -> Date
```
## DoD
- [x] UsersConfirmationTypes
- [x] UsersConfirmationSchema
- [x] UsersConfirmatonRepository
- [x] UserConfirmationCreator use case
- [x] Update UserRegister use-case to call UserConfirmationCreator
- [x] Remove call from controller
- [x] Update UserConfirmer to use new collection
- [x] Passing tests
